### ISSUE TITLE
DeprecationWarning: ssl.wrap_socket() is deprecated

### ISSUE THREAD

**Issue by alliesw** [advanced-threat-research/NetLlix#1]
$ python3 HTTP-S-EXFIL.py ssl
/home/kali/Desktop/NetLlixV0.1/WebServer/HTTP-S-EXFIL.py:27: DeprecationWarning: ssl.wrap_socket() is deprecated, use SSLContext.wrap_socket()
  httpd.socket = ssl.wrap_socket(httpd.socket,
INFO:root:Starting secure httpd...

**Comment by kartikdurg** [comment]
Since it's just a warning I am closing the issue.

Without any warning on my kali VM:

![image](https://user-images.githubusercontent.com/20142153/210589112-cd12ba14-c45c-43c0-b95b-8453920e06a1.png)
